server:
  port: 80
spring:
  application:
    name: miujoke-order-service

eureka:
  client:
    register-with-eureka: true    #表识向注册中心注册自己
    fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
