server:
  port: 80
spring:
  application:
    name: miujoke-hystrix-order-service

eureka:
  client:
    register-with-eureka: true    #表识向注册中心注册自己
    fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址  ：：单机版
      #defaultZone: http://eureka7002.com:7001/eureka,http://eureka7002:7002/eureka  #集群版

  #设置OpenFeign客户端超时时间（OpenFeign默认支持ribbon）
  #ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  #ReadTimeout: 5000
  #指的是简历连接所有的时间，适用于网络状况正常的情况下，两端连接所有的时间
  #ConnectRimeout: 5000
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
# 新版基本使用当前这种模式
feign:
  client:
    config:
      default:
        # 连接超时
        connect-timeout: 50000
        #读取超时
        read-timeout: 50000
  hystrix:
    enabled: true
logging:
  level:
    com.miujoke.service.OpenFeignPaymentService: debug