server:
  port: 8001


spring:
  application:
    name: cloud-payment-service  # 注册中心的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://192.168.0.128:3306/miujoke-springcloud?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin

eureka:
  client:
    register-with-eureka: true    #表识向注册中心注册自己
    fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.miujoke.entities # 所有entity别名类所在包