server:
  port: 9001


spring:
  application:
    name: miujoke-auth2-jdbc  # \u6CE8\u518C\u4E2D\u5FC3\u7684\u540D\u5B57
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # \u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql\u9A71\u52A8\u5305
    url: jdbc:mysql://192.168.44.128:3306/oauth2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
