server:
  port: 83

spring:
  application:
    name: nacos-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8088 #转到nginx集群
        ip: 192.168.1.6

service-url:
  nacos-user-service: http://nacos-payment-provider
